# Generated by Django 4.0.2 on 2022-02-18 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='nome_projeto',
            field=models.CharField(default='', max_length=50),
        ),
    ]
