# Generated by Django 4.0.2 on 2022-03-17 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0002_projeto_nome_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='foto',
            field=models.ImageField(upload_to='static/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='perfil_img',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
