# Generated by Django 4.0.2 on 2022-03-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0003_alter_inicio_foto_alter_sobre_perfil_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inicio',
            name='foto',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(upload_to='static/img/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='perfil_img',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
