# Generated by Django 4.0.2 on 2022-03-23 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0004_alter_inicio_foto_alter_projeto_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(upload_to='projetos/'),
        ),
    ]
