# Generated by Django 4.0.2 on 2022-04-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0006_alter_inicio_foto_alter_sobre_perfil_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(default='', max_length=50)),
                ('imagem', models.ImageField(upload_to='Certificados/')),
                ('link', models.URLField()),
            ],
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='imagem',
            new_name='imagem_certificado',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='link',
            new_name='link_certificado',
        ),
    ]
