# Generated by Django 4.0.2 on 2022-04-05 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0007_certificado_rename_imagem_projeto_imagem_certificado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='imagem',
            field=models.FileField(upload_to='Certificados/'),
        ),
    ]
