# Generated by Django 4.0.2 on 2022-04-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0008_alter_certificado_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='imagem',
            field=models.ImageField(upload_to='Certificados/'),
        ),
    ]
