# Generated by Django 4.0.2 on 2022-04-05 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0009_alter_certificado_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificado',
            old_name='imagem',
            new_name='imagem_certificado',
        ),
        migrations.RenameField(
            model_name='certificado',
            old_name='link',
            new_name='link_certificado',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='imagem_certificado',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='projeto',
            old_name='link_certificado',
            new_name='link',
        ),
    ]
