# Generated by Django 4.0.4 on 2022-04-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0010_rename_imagem_certificado_imagem_certificado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='github_link',
            field=models.URLField(default=''),
        ),
    ]
