# Generated by Django 4.0.4 on 2022-04-19 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0011_projeto_github_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='github_link',
            new_name='github',
        ),
    ]
