# Generated by Django 4.0.4 on 2022-04-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0012_rename_github_link_projeto_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='github',
            new_name='github_link',
        ),
    ]
