# Generated by Django 4.0.4 on 2022-04-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0014_alter_certificado_imagem_certificado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sobre',
            name='perfil_img',
        ),
        migrations.AlterField(
            model_name='certificado',
            name='imagem_certificado',
            field=models.ImageField(upload_to='Certificados/'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='foto',
            field=models.ImageField(upload_to='Perfil/'),
        ),
    ]
