# Generated by Django 4.0.4 on 2022-04-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alefe', '0016_alter_inicio_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='imagem_certificado',
            field=models.ImageField(upload_to='s3.amazonaws.com/alefeportfolio/media/Certificados/'),
        ),
        migrations.AlterField(
            model_name='inicio',
            name='foto',
            field=models.ImageField(upload_to='s3.amazonaws.com/alefeportfolio/media/Perfil'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(upload_to='s3.amazonaws.com/alefeportfolio/media/projetos/'),
        ),
    ]
